DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO v_exists
    FROM user_tables
    WHERE table_name = 'AUDITLOG';
    
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE AuditLog (
            LogID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            TransactionID NUMBER,
            AccountID NUMBER,
            TransactionDate DATE,
            Amount NUMBER,
            TransactionType VARCHAR2(10),
            LogDate DATE DEFAULT SYSDATE
        )';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog (TransactionID, AccountID, TransactionDate, Amount, TransactionType, LogDate)
    VALUES (:new.TransactionID, :new.AccountID, :new.TransactionDate, :new.Amount, :new.TransactionType, SYSDATE);
END;
/
